packages:
  # 所有在 packages/ 下的 package
  - 'base'
  - 'demo'
  - 'react-app'
  - 'vue-app'
  - 'game'
  - 'login'
  - 'three'
  - 'step-page'
  - 'database'
  # 不包括在 test 文件夹下的 package
  # - '!**/test/**'